[workspace]
members = ["api", "secure-enclave", "shared/enclave-types"]
resolver = "3"

[workspace.package]
edition = "2024"
version = "0.1.0"
license = "MIT"
publish = false

[workspace.lints.clippy]
all = "deny"
pedantic = "deny"
nursery = "deny"

[workspace.lints.rust]
dead_code = "deny"
missing_docs = "deny"

[workspace.dependencies]
anyhow = "1.0"
axum = "0.8"
enclave-types = { path = "shared/enclave-types" }
pontifex = { version = "1.1.2", default-features = false }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.48", features = ["macros", "net", "rt-multi-thread", "signal"] }
tower = { version = "0.5", features = ["util"] }
tower-http = { version = "0.6", features = ["trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
