[package]
name = "di-host"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "di-host"
path = "src/main.rs"

[dependencies]
di-types.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
