[package]
name = "deepface-host"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "deepface-host"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
axum.workspace = true
base64.workspace = true
deepface-types.workspace = true
enclave-types.workspace = true
hex = { workspace = true, features = ["serde"] }
pontifex = { workspace = true, features = ["client"] }
rand.workspace = true
serde.workspace = true
thiserror.workspace = true
telemetry-batteries.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
async-trait.workspace = true
tokio = { workspace = true, features = ["test-util"] }
http-body-util = "0.1"
serde_json.workspace = true
tower.workspace = true
