[package]
name = "verifier-client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
aws-nitro-enclaves-nsm-api.workspace = true
base64.workspace = true
ciborium.workspace = true
coset.workspace = true
hex.workspace = true
p384.workspace = true
reqwest.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true
webpki.workspace = true
x509-cert.workspace = true

[dev-dependencies]
axum.workspace = true
hex-literal.workspace = true
sha2.workspace = true
tokio.workspace = true
