[package]
name = "deepface-e2e"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
attested-channel.workspace = true
deepface-protocol.workspace = true
hex.workspace = true
rand.workspace = true
sha2.workspace = true
tokio.workspace = true
deepface-client.workspace = true
