[package]
name = "secure-enclave"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "secure-enclave"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
ark-babyjubjub.workspace = true
ciborium.workspace = true
eddsa-babyjubjub.workspace = true
enclave-types = { workspace = true, features = ["sealing"] }
face-engine.workspace = true
hex.workspace = true
hpke.workspace = true
image.workspace = true
pontifex = { workspace = true, features = ["nsm", "server"] }
rand.workspace = true
serde = { workspace = true }
serde_bytes.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
