[package]
name = "secure-enclave"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "secure-enclave"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
enclave-types.workspace = true
pontifex.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
