[package]
name = "deepface-enclave"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "deepface-enclave"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
ark-babyjubjub.workspace = true
attested-channel.workspace = true
ciborium.workspace = true
deepface-enclave-types.workspace = true
deepface-protocol.workspace = true
eddsa-babyjubjub.workspace = true
face-engine.workspace = true
getrandom.workspace = true
hex.workspace = true
image.workspace = true
pontifex = { workspace = true, features = ["nsm", "server"] }
rand.workspace = true
serde.workspace = true
serde_bytes.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
